export { default as Login } from './login/Login'
export { default as Signup } from './signup/Signup'
export { default as Home } from './home/Home'
export { default as Cart } from './cart/Cart'
export { default as AddProduct } from './add-product/AddProduct'